max_simulation_time: 10
delta_t: 0.1
lqr:
  model_type: "path"
  N: 20
  nx: 5
  nu: 2
  w_pos: 1.0
  w_vel: 1.0
  w_yaw: 20.0
  w_heading: 20.0
  w_kappa: 10.0
  w_acc: 0.5
  w_stl: 30.0
  w_dkappa: 30.0
  slove_type: "alm"
  ref_x_weight: 1.0
  final_x_weight: 10.0
  uki_init: 20.0
  alm_rho_init: 20.0
  alm_gamma: 0.1
  max_rho: 100.0
  max_mu: 200.0
  obstacle_exp_q1: 8.0
  obstacle_exp_q2: 6.0
  state_exp_q1: 3.0
  state_exp_q2: 3.6
  use_last_solution: true
iteration:
  max_iter: 15
  init_lamb: 5.0
  lamb_decay: 0.7
  lamb_amplify: 5.0
  max_lamb: 600.0
  convergence_threshold: 0.05
  accept_step_threshold: 0.3
vehicle:
  reference_point: "rear_center"
  target_velocity: 9
  wheelbase: 2.8
  width: 2
  length: 4.5
  velo_max: 10.0
  velo_min: 0.0
  yaw_lim: 1.57
  acc_max: 3.0
  acc_min: -3.0
  stl_lim: 0.12
  d_safe: 0.9
  kappa_max: 0.3
  kappa_min: -0.3
  dkappa_max: 0.1
  dkappa_min: -0.1
laneline:
  reference:
    x: [-10, 0, 50, 100, 150, 200]
    y: [7.2, 7.2, 7.2, 7.2, 7.2, 7.2]
  border: [-9, -5.4, -1.8, 1.8]
  center_line: [0, -3.6, -7.2]
initial_condition:
  - [0, 0, 6.0, 0]
  - [20, 0, 3.0, 0]
  - [40, 0, 3.0, 0]
  - [50, 0, 3.0, 0]
  - [0, 3.6, 5.0, 0]
  - [35, 3.6, 5.0, 0]
  - [50, 3.6, 5.0, 0]
  - [5, 7.2, 7, 0]
  - [50, 7.2, 6.0, 0]
visualization:
  y_lim: [-3, 17]
  show_obstacle_boundary: false
